include:
  - board: xiao_ble
    shield: cool642tb_L
    extra-modules: [zmk-rgbled-widget]
    env:
      CONFIG_ZMK_BOARD_COMPAT: "y"

  - board: xiao_ble
    shield: cool642tb_R
    snippet: studio-rpc-usb-uart
    extra-modules: [zmk-rgbled-widget]
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    env:
      CONFIG_ZMK_BOARD_COMPAT: "y"

  - board: xiao_ble
    shield: settings_reset
